services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms:
        - linux/amd64
    container_name: fpl-api
    environment:
      - DATABASE_URL=postgres://fpl_user:fpl_password@db:5432/friend_leaderboards?sslmode=disable
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: fpl-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: friend_leaderboards
      POSTGRES_USER: fpl_user
      POSTGRES_PASSWORD: fpl_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
      # Uncomment to run init scripts on first start
      # - ./postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
